spring:
  application:
    name: crud
  datasource:
    url: jdbc:h2:mem:crud
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
   
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          introspection-uri: http://localhost:8081/oauth/check_token
#          client-id: checktoken
#          client-secret: check123

crud-api:
  email:
    remetente: Crud-API-Evollo - <junior_rui@yahoo.com.br>
    