spring:
  application:
    name: crud
  datasource:
    url: jdbc:h2:mem:crud
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8081/oauth/check_token
          client-id: checktoken
          client-secret: check123
